services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: news_app
    ports:
      - "3000:3000"
    environment:
      APP_PORT: 3000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: newsdb
      DB_SSLMODE: disable
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ""
      REDIS_DB: 0
      REDIS_TTL: 300
    volumes:
      - .:/app
      - go_cache:/root/go/pkg/mod
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - news_network
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    container_name: news_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: newsdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - news_network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: news_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - news_network
    restart: unless-stopped

  redisinsight:
    image: redis/redisinsight:latest
    container_name: news_redisinsight
    ports:
      - "5540:5540"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - news_network
    restart: unless-stopped

volumes:
  postgres_data:
  go_cache:

networks:
  news_network:
    driver: bridge
